### PR TITLE
Merge implementation for message filters.

### LINKED ISSUE #25: Support filters on error messages
The ability to use angular filters on messages would be pretty helpful to a lot of people, I for one. We should allow developers to specify one of more filters, in the order to apply them, that will then be applied when resolving/fetching the error message for a field validation issue.

To configure message filters...

Via config: bValidationConfig.global.useMessageFilters('' or []);
Via attribute: <key>-notification-filter="<filterName>"

If the attribute is specified, it will use those over the config specified ones; a kind of override.

### PR DESCRIPTION
**Pull request by ShaneYu**
This is a pull-request for the implementation of message filters.

I have also updated the documentation, but until a new version of the package is deployed to bower, I will not merge the documentation; otherwise the examples coded in codepen for the new feature will not work.

Once this has been merged and a new version pushed to bower, I will put in a merge request for the documentation.

Closes #25.

### CODE REVIEW

**Comment by ShaneYu** [comment]
Thanks for doing this merge, I've got the doc updates to merge next but my plunkrs are using the old 1.4.1 on CDN. When are you likely to do the next release?

I wouldn't want to merge the docs in where the examples don't work.

**Comment by sagrawal31** [comment]
@ShaneYu released 1.0.5 https://github.com/sagrawal14/bootstrap-angular-validation/releases/tag/v1.0.5

**Comment by ShaneYu** [comment]
@sagrawal14 Thanks for this, however I've noticed that the release file is not up to date, though this may be my fault.

Do you usually commit the dist folder after building changes locally? If so, then apologies as other projects I've worked on usually only check in src and never dist. If this is the case then it will need to be built and commit again; and sadly the release updating.

Does your dev process include committing the dist folder for releases?
Would you like me to build it and commit the dist in for a new merge?

Apologies

**Comment by ShaneYu** [comment]
@sagrawal14 When you have chance, please could you read my comment above. I've still got the documentation updates ready to request a merge for once the latest release has been sorted out. Cheers, Shane.

**Comment by sagrawal31** [comment]
Hey @ShaneYu, I had missed committing the minified files. Currently, I do the build manually which results in this mistake. I just released version `v1.0.5-1` having the latest code with minified files.

**Pull request merged**
